# Visit https://discord.com/developers/applications for your bot token
BOT_TOKEN: 'your bot token'

# The character prefix for chat commands
COMMAND_CHAR: '!'

# Database info
DB_HOST: 'localhost'
DB_PORT: '27017'
DB_NAME: 'DFPedia'
DB_COLLECTION: 'weapons_and_accessories'
DB_AUTH_MECHANISM: 'DEFAULT'
DB_USER: 'username'
DB_PASS: 'password'

ELASTIC_URL: 'https://localhost:9200'
ELASTIC_USER: 'username'
ELASTIC_PASS: 'password'
PET_INDEX_NAME: 'dragonfable-pets'
ACCESSORY_INDEX_NAME: 'dragonfable-accessories'

# Channel IDs in which long sort results will be posted (such as a dedicated bot spam channel)
# In all other channels, only short results will be displayed (<= top 3 items) when the command is used
LONG_RESULT_CHANNELS: []

# The ID to be pinged in case an error occurs
DEV_ID: ''
