# Visit https://discord.com/developers/applications for your bot token
BOT_TOKEN: 'your bot token'

# The character prefix for chat commands
COMMAND_CHAR: '!'

# Database info
DB_HOST: 'localhost'
DB_PORT: '27017'
DB_NAME: 'DFPedia'
DB_COLLECTION: 'weapons_and_accessories'
DB_AUTH_MECHANISM: 'DEFAULT'
DB_USER: 'username'
DB_PASS: 'password'

ELASTIC_URL: 'https://localhost:9200'
ELASTIC_USER: 'username'
ELASTIC_PASS: 'password'
PET_INDEX_NAME: 'dragonfable-pets'

# The ID to be pinged in case an error occurs
DEV_ID: ''
