export const PET_ALIASES = {
    tfs: 'rare pet tog',
    ex: 'extreme',
};
export const ACCESSORY_ALIASES = {
    k: 'thousand',
    '1k': 'thousand',
    adl: 'ancient dragonlord helm',
    ba: "baltael's aventail",
    bsw: "baltael's aventail",
    c7: 'the corrupted seven',
    ddb: 'defenders dragon belt',
    ddn: 'defenders dragon necklace',
    ddr: 'defenders dragon ring',
    ddv: 'distorted doom visage',
    drk: 'dragonknight',
    eud: 'elemental unity defender',
    fdl: 'fierce dragonlord',
    dlc: 'dragonlord captain',
    gt: 'grove tender',
    ngt: 'neo grove tender',
    nstb: 'not so tiny bubbles',
    pdl: "dragon's patience",
    rdl: "dragon's rage",
    bdl: "dragon's bulwark",
    wdl: "dragon's wrath",
    sf: 'soulforged',
    ttv: 'tytanvisage',
    df: 'dragonfable',
    dl: 'dragonlord',
    amogus: 'amalgam',
};
export const WEAPON_ALIASES = {
    adsoe: 'ancient dragon amulet scythe of the elements',
    ba: 'baltaels aventail',
    blod: 'blinding light of destiny',
    boa: 'blade of awe',
    bod: 'blade of destiny',
    ddsoe: 'doomed dragon amulet scythe of the elements',
    ddsoe1: 'doomed dragon amulet scythe of elementals',
    ddsoe2: 'doomed dragon amulet scythe of the elements',
    drk: 'dragonknight',
    dsod: 'dragonstaff of destiny',
    fc: 'frozen claymore',
    fs: 'frostscythe',
    gg: 'forgotten gloom glaive',
    gt: 'grove tender',
    isis: 'ice scythe',
    lh: 'lucky hammer',
    npsb: 'necro paragon soulblade',
    nsod: 'necrotic sword of doom',
    scc: 'sea chickens conquest',
    sf: 'soulforged',
    tbod: 'twin blades of destiny',
    udsod: 'ultimate dragonstaff of destiny',
    ublod: 'ultimate blinding light of destiny',
    utbod: 'ultimate twin blades of destiny',
    uok: 'ultra omniknight',
    vik: 'vanilla ice katana',
};
